[WIP] Jet Stirred Reactors
kyleniemeyer/PyTeCK pull request #17
Opened 2019-08-15 11:07 UTC by skrsna

- [ ] Ready for review
* Code is functional and successfully runs JSRs given a ChemKED JSR file (https://github.com/pr-omethe-us/PyKED/pull/126) 

### Todo:
- [ ] Multiprocessing 
- [ ] Efficently save .h5 files 
- [ ] Refactoring 
   - [ ] `eval_model.py`
   - [ ] `simulation.py` 
- [ ] Error functions 
   - [x] Difference between area under the curves using `numpy.trapz`

2019-08-16 15:01 UTC, rwest commented
I would suggest integrate the difference between the curves, rather than find the difference of the integrals.

2019-08-16 19:43 UTC, kyleniemeyer commented
> I would suggest integrate the difference between the curves, rather than find the difference of the integrals.

I'm trying to visualize the difference here... in practice the answer should be the same, no? Though it's easier/more efficient to just integrate once.

2019-08-16 20:29 UTC, rwest commented
I was imagining these two curves

<img width="384" alt="Screen Shot 2019-08-16 at 4 27 15 PM" src="https://user-images.githubusercontent.com/93807/63196229-cb23b400-c042-11e9-8f6f-76c4e0f9b866.png">

They have the same area under them, so the difference in area under curve is zero, suggesting they are identical and there is no error in the model.


If you find the difference between the curves, then the area between that and the y=0 axis (ok, so perhaps I should have said integrate the absolute value of the difference between the curves), the error is significant.


<img width="738" alt="Screen Shot 2019-08-16 at 4 27 19 PM" src="https://user-images.githubusercontent.com/93807/63196313-fe664300-c042-11e9-8530-48e71d363132.png">

2019-08-16 20:30 UTC, kyleniemeyer commented
@rwest got it, that makes sense!

2019-08-16 20:33 UTC, rwest commented
It's by no means a perfect measure of fit. For example, these two pairs of curves would have the same "error".

<img width="241" alt="Screen Shot 2019-08-16 at 4 33 20 PM" src="https://user-images.githubusercontent.com/93807/63196576-92380f00-c043-11e9-84f8-b7a8257f3928.png">

But it's a start, to get the code working.

2019-08-16 20:38 UTC, kyleniemeyer commented
Agreed. 

FYI, when I was implementing the error evaluation for perfectly stirred reactor simulations in my older MARS, which marched along the upper branch, I used three points: near extinction turning point, near equilibrium (e.g., a residence time of around 0.1 s, and the logarithmic midpoint between those two points.

The overall error was the the max of the error in residence time at the extinction turning point and the error in temperature at the other two points.

2019-09-10 19:54 UTC, rwest commented on pyteck/simulation.py
> +                timestep.append()
JSR simulations needn't save time history.
Probably this whole method should be in the AutoIgnitionSimulation class, not the Simulation super-class

2021-06-09 14:55 UTC, rwest commented
For our JSR simulations it's maybe worth reading [2E08.pdf](https://github.com/pr-omethe-us/PyTeCK/files/6624745/2E08.pdf) and keeping an eye on https://github.com/Cantera/enhancements/issues/31 and https://github.com/Cantera/cantera/pull/1021

2022-02-24 15:55 UTC, sevyharris commented
I'm resurrecting this PR because I've got a flame speed addition in the works that depends on this.

Here's what I've done:
- Finished adding multiprocessing
- Added handling for multiple datasets
- Made a bunch of PEP8/style changes because I can't help myself
- Refactored the simulation files back into a single simulation.py file

Here's the remaining work:
[ ] Get existing tests back up and running
[ ] Add JSR tests
[ ] Refactor jsr_eval_model into eval_model

Here's what I don't plan to do for this PR:
- Improve the error calculations. I made a curve_matching branch that can (in theory) handle this, but it deserves its own PR
- Plotting

2022-02-24 16:04 UTC, rwest requested changes
Incomplete review; going to wait until refactoring finished. Not clear to me yet how multiple different simulation types are going to coexist and reuse appropriate code/classes.

2022-02-24 16:04 UTC, rwest commented on pyteck/eval_model.py
> +from .simulation import AutoIgnitionSimulation as Simulation
In general I'm not sure I like the idea of importing something under a different name - could likely confuse people down the line. Is there a good reason for it?

2022-02-24 16:04 UTC, rwest commented on pyteck/eval_model.py
> +        List of :class:`AutoignitionSimulation` objects for each simulation
Perhaps I should wait to review until refactoring finished, but this file/module/class seems a little confused right now about if it's specific to Autoignition, or if it's generic for all simulations. 

So I'm going to pause reviewing now. Let me know if/when I should take another look.

2022-02-28 14:44 UTC, sevyharris commented
Okay, @rwest I think this one is ready for review.

2026-05-17 00:51 UTC, closed without merging